<a href="https://colab.research.google.com/github/code-Lance/deep_learning/blob/main/week_1_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 당뇨병 데이터를 가지고 머신러닝 5가지 분류를 수행.

# 필요한 라이브러리 불러오기

In [127]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

# 데이터 불러오기

In [128]:
# 데이터 불러오기
url = 'https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/diabetes.csv'
df = pd.read_csv(url)

# 데이터 확인
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# 결측치 확인 및 제거


In [129]:
# 결측치 확인
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# 테스트, 훈련 데이터로 분류

In [130]:
# 테스트, 훈련 데이터 나누기 (X = 당뇨병인지 확인할 수 있는 여러 요소들, Y = 당뇨병 유무 결과)
X = df.drop('Outcome', axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)


# SVM 분류

In [131]:
# SVM (Support Vector Machine) 분류
clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)
pred_svm = clf_svm.predict(X_test)
print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.7708333333333334
[[119  11]
 [ 33  29]]


# LR 분류

In [132]:
# LR (Logistic Regression) 분류
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.7916666666666666
[[115  15]
 [ 25  37]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# RF 분류

In [133]:
# RF(Random Forest) 분류
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.7916666666666666
[[115  15]
 [ 25  37]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# DT 분류


In [134]:
# DT(Decision Tree) 분류
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.71875
[[102  28]
 [ 26  36]]


# KNN 분류

In [135]:
clf_knn = KNeighborsClassifier()
clf_knn.fit(X_train, y_train)
pred_knn = clf_knn.predict(X_test)

print ("\n--- K-Nearest Neighbors Classifier ---")
print (accuracy_score(y_test, pred_knn))
print (confusion_matrix(y_test, pred_knn))


--- K-Nearest Neighbors Classifier ---
0.7552083333333334
[[109  21]
 [ 26  36]]


# 2. 동일한 데이터로 딥러닝 분류 수행하라.

In [136]:
# 데이터 불러오기
url = 'https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/diabetes.csv'
df2 = pd.read_csv(url)
df2

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# 테스트, 훈련 데이터로 분류

In [137]:
# 테스트, 훈련 데이터 나누기 (X = 당뇨병인지 확인할 수 있는 여러 요소들, Y = 당뇨병 유무 결과)
X = df2.drop('Outcome', axis=1)
y = df2['Outcome']
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y,test_size=0.25,random_state=0)

In [138]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [139]:
# 모델 컴파일 (optimizer: Adam, loss: binary_crossentropy, metrics: accuracy)
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [140]:
# 모델 학습
model.fit(X_train2, y_train2, epochs=50, batch_size=16, validation_split=0.2, verbose=1)


Epoch 1/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.4242 - loss: 5.5818 - val_accuracy: 0.4052 - val_loss: 2.1681
Epoch 2/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5278 - loss: 1.5336 - val_accuracy: 0.5517 - val_loss: 1.2351
Epoch 3/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5446 - loss: 1.2624 - val_accuracy: 0.4914 - val_loss: 1.1473
Epoch 4/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6110 - loss: 1.0819 - val_accuracy: 0.5259 - val_loss: 0.9729
Epoch 5/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5838 - loss: 0.9432 - val_accuracy: 0.6638 - val_loss: 1.0864
Epoch 6/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6022 - loss: 0.9359 - val_accuracy: 0.6552 - val_loss: 0.8813
Epoch 7/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6264 - loss: 0.8687 - val_accuracy: 0.6724 - val_loss: 0.9057
Epoch 8/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6162 - loss: 0.7968 - val_accuracy: 0.5000 - val_loss

In [141]:
# 모델 평가
loss, accuracy = model.evaluate(X_test2, y_test2, verbose=0)
print(f'Deep Learning Model Accuracy: {accuracy}')

Deep Learning Model Accuracy: 0.6666666865348816


# 3. 해당 데이터에서 Outcome을 삭제하고 BMI를 예측하는 회귀를 수행하라.

# 데이터 불러오기

In [142]:
# 데이터 불러오기
url = 'https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/diabetes.csv'
df3 = pd.read_csv(url)
df3

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# 테스트, 훈련 데이터로 분류

In [143]:
# 테스트, 훈련 데이터 나누기 (X = bmi를 추정할 수 있는 요소들, Y = bmi)
X = df3.drop(['Outcome', 'BMI'], axis=1) # outcome 삭제, bmi는 예측요소이므로 제거
y = df3['BMI'] # 예측하고자 하는 대상은 bmi
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y,test_size=0.25,random_state=0)

In [144]:
# 사용할 회귀 모델 리스트 생성
regressors = {
    'Linear Regression': LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(),
    'Decision Tree Regressor': DecisionTreeRegressor(),
    'Support Vector Regressor': SVR(),
    'K-Nearest Neighbors Regressor': KNeighborsRegressor()
}

In [145]:
from sklearn.metrics import mean_squared_error
# 각 회귀 모델 학습 및 테스트 데이터로 예측
for name, model in regressors.items():
    # 모델 학습
    model.fit(X_train, y_train)
    # 테스트 데이터로 BMI 예측
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    print(f'{name} MSE: {mse:.2f}')  # 모델의 평균 제곱 오차 출력

Linear Regression MSE: 0.15
Random Forest Regressor MSE: 0.14
Decision Tree Regressor MSE: 0.26
Support Vector Regressor MSE: 0.16
K-Nearest Neighbors Regressor MSE: 0.18


# 4. 3번과 동일하지만 dense layer만 사용한 신경만으로 회귀를 수행하라.



In [146]:
# 데이터 불러오기
df = pd.read_csv(url)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [147]:
# 테스트, 훈련 데이터 나누기 (X = bmi를 추정할 수 있는 요소들, Y = bmi)
X = df.drop(['Outcome', 'BMI'], axis=1) # outcome 삭제, bmi는 예측요소이므로 제거
y = df['BMI'] # 예측하고자 하는 대상은 bmi
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [148]:
# 신경망 모델 구축
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [149]:
# 모델 컴파일
model.compile(optimizer = 'rmsprop', loss = 'mse', metrics = ['mse'])

# 모델 학습
model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))

# 테스트 데이터로 예측 수행
y_pred = model.predict(X_test)

# 예측 결과와 실제 값 출력
mse = mean_squared_error(y_test, y_pred)
print(f'Neural Network MSE: {mse:.2f}')  # 평균 제곱 오차 출력

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 274.0518 - mse: 274.0518 - val_loss: 73.4042 - val_mse: 73.4042
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 56.8507 - mse: 56.8507 - val_loss: 63.3381 - val_mse: 63.3381
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 72.3717 - mse: 72.3717 - val_loss: 66.1453 - val_mse: 66.1453
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 49.2347 - mse: 49.2347 - val_loss: 70.4289 - val_mse: 70.4289
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 58.8698 - mse: 58.8698 - val_loss: 69.0007 - val_mse: 69.0007
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 52.0391 - mse: 52.0391 - val_loss: 68.7371 - val_mse: 68.7371
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 49.6110 - mse: 49.6110 - val_loss: 69.2504 - val_mse: 69.2504
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53.0130 - mse: 53.0130 - val_loss: 58.5358 - val_mse: 58.5358
Epoch 9/100
18/18 ━━━━━━━━━━━